### ISSUE TITLE
Constructor has not yet been ported to this platform

### ISSUE THREAD

**Issue by Mechlus** [SortaCore/MMF2Exts#20]
![image](https://github.com/SortaCore/MMF2Exts/assets/82886093/2b90c8b4-c958-49ae-a17f-57cb4564f286)
(In bitset)
I've recently gotten this message and even after reinstalling this repo, I still get the same error. This is on line 275 and occurs for Android. I have built extensions before and only recently this has been appearing.

**Comment by SortaCore** [comment]
It's an IntelliSense bug. Switch the dropdown from Build + IntelliSense to just Build, should be fine :+1:

**Comment by Mechlus** [comment]
Worked! Thanks a ton.

**Comment by SortaCore** [comment]
Eventually, if I can, I'll try to get VS IntelliSense sorted. It's Microsoft's bug, though.

I did put [notes for iOS/Mac IntelliSense](https://github.com/SortaCore/MMF2Exts/blob/master/DarkEdif/%23MFAs%20and%20documentation/DarkEdif%20MultiTargeting.md#intellisense-is-out-of-date), but ultimately Visual Studio IntelliSense doesn't support Objective-C++, so it's always giving false positives.

For Android, though, it should have no excuse... maybe the preprocessor defines IntelliSense is aware of, versus what the compiler actually gets, are different.
